name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Remove Residual Files
      run : |
        rm -f test runscript test_log.txt
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "[Bot] Github Actions deleted residual files!"
          git push
        fi

    - name: Run MakeFile
      run: make

    - name: Run Tests
      run: ./test
