name: C/C++ CI

on:
  push:
    main: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Remove Residual Files
      run : |
        if [ ! -f test ] && [ ! -f runscript ] && [ ! -f test_log.txt ]; then
          echo "No residual files found, skipping commit."
        else
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          rm -f test runscript test_log.txt
          git commit -a -m "[Bot] Github Actions deleted residual files!"
          git push origin HEAD:$(echo $GITHUB_HEAD_REF | sed 's/refs\/heads\///')
        fi

    - name: Run MakeFile
      run: make

    - name: Run Tests
      run: ./test
